### ISSUE TITLE
Does this only work with shelley era?

### ISSUE THREAD

**Issue by mzfr** [input-output-hk/cardano-clusterlib-py#52]
I was trying this out and got the following error:

```
cardano_clusterlib.clusterlib.CLIError: An error occurred running a CLI command `cardano-cli transaction submit --testnet-magic 1097911063 --tx-file send_funds_tx.signed --cardano-mode` on path `/home/pwnbox/cardano`: Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash "44d0f363b17fe23435609fd2e9bc5bf8b7379c11597320789a20b97d")) StakeRefNull,Value 206721 (fromList [(PolicyID {policyID = ScriptHash "6b8d07d69639e9413dd637a1a815a7323c69c86abbafb66dbfdb1aa7"},fromList [("",2)])]),SNothing)])))])
```

I believe in the `state_dir` I provided the `shelley-genesis.json`. Should I be providing, `alonzo/genesis.json`?

**Comment by mkoura** [comment]
The important part is `OutputTooSmallUTxO`. That happens when one of the transaction outputs is less than minimal amount, which is around 1 ADA on mainnet. It can be either the amount you are trying to transfer, or the resulting change.

**Comment by mzfr** [comment]
@mkoura Yes I actually looked at it, I was testing on testnet and in the UTxO I had 100 tADA, and I was trying to transfer 10 ADA so not sure why would that happen.

**Comment by mkoura** [comment]
Can you post how you called the python function? Or do you have the transaction file? The only idea I have is that you specified output for change in addition to the 10 tADA transfer, and the change amount was not precise.

**Comment by mzfr** [comment]
```python
from cardano_clusterlib import clusterlib
import sys


SRC_ADDR = "MY_ADDR"


def main():
    dst_addr = sys.argv[1]
    amt = int(sys.argv[2])*1000000
    print(dst_addr, amt)
    cluster = clusterlib.ClusterLib(state_dir="cardano/testnet/configs")
    destination = [clusterlib.TxOut(address=dst_addr, amount=amt)]
    tx_files = clusterlib.TxFiles(signing_key_files=["cardano/payments/payment_addr_1/payment.skey"])
    
    tx_raw_output = cluster.send_funds(
        src_address=SRC_ADDR,
        destinations=destination,
        tx_name="send_funds",
        tx_files=tx_files,
    )

    cluster.wait_for_new_block(new_blocks=2)
    cluster.get_utxo(dst_addr)

if __name__ == "__main__":
    main()

```

I call this script in the following way:

```bash
python3 transfer_ada.py <ANOTHER_ADDR> 10
```

**Comment by mkoura** [comment]
Thanks @mzfr!
When used this way, without specifying input UTxOs explicitly (`send_tx(txins=...`), the UTxOs are selected so that their total tADA amount can satisfy all transaction outputs and fee. Unfortunately minimum change value is not taken into consideration, so it can happen that the remaining change is lower than allowed and the change UTxO cannot be created.
I should probably hardcode a meaningful default for min change value that works for testnet and mainnet instead of 0 (until I come up with more precise computation). In the meantime, you can do

```python
cluster = clusterlib.ClusterLib(state_dir="cardano/testnet/configs")
cluster._min_change_value = 1500_000
```

**Comment by mkoura** [comment]
I've changed the hardcoded `_min_change_value` from 0 to 1800000 Lovelace. The code that selects input UTxOs will take it into account. It is released in https://pypi.org/project/cardano-clusterlib/0.1.48/

**Comment by mzfr** [comment]
@mkoura Thanks for updating this. I'll try it out with the latest version and then close this issue if I don't encounter any problem with it.

**Comment by mzfr** [comment]
@mkoura This works like a charm, thanks once again :)
