### ISSUE TITLE
_select_utxos() function not factoring in the minimum output UTXO amount

### ISSUE THREAD

**Issue by sdbriney** [input-output-hk/cardano-clusterlib-py#57]
I believe that the _select_utxos() function is not factoring in the minimum output UTXO amount which can cause the send_funds() to fail in some situations.

Here is my example: -

At my source address, I have 2 UTxOs

They have the following values:
2000000 lovelace
2954210 lovelace

I try to send 2000000 lovelace to another address using the function send_funds(). This ultimately calls _select_utxos(). The _select_utxos() function selects the UTxO with 2954210 lovelace. The code then generates the following output UTxOs 1803720 (2000000 - fee) and 954210 change back to my address. The problem is that 954210 is less than the minimum UTxO amount and I get an OutputTooSmallUTxO error.

From what I understand the _select_utxos() function should be changed to select enough UTxOs to cover the exact amount required or if the amount selected is greater than the required amount (and therefore change will be generated), the remainder amount (change) needs to be greater than the minimum UTxO amount. If the remaining amount is too small it should select more UTxOs if available.

**Comment by mkoura** [comment]
Hi @sdbriney , is your issue resolved by https://github.com/input-output-hk/cardano-clusterlib-py/pull/55 ? This fix is included in the released version 0.1.48.

**Comment by sdbriney** [comment]
Hi @mkoura this looks very promising. I have just checked and I'm on 0.1.47! I will update the code, test it again and feedback. Thank you for your help.

**Comment by sdbriney** [comment]
Hi. Yes, version 0..1.48 has fixed this. Thanks for your help @mkoura
